module.exports = {
    printWidth: 120,
    tabWidth: 4,
    tabs: false,
    semi: true,
    singleQuote: false,
    quoteProps: "consistent",
    jsxSingleQuote: true,
    trailingComma: "es5",
    bracketSpacing: false,
    jsxBracketSameLine: false,
    arrowParens: "always",
    proseWrap: "preserve",
    htmlWhitespaceSensitivity: "strict",
};
